version: '3'
services:
  mktp-web-nginx:
    container_name: mktp-web-nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
      args:
        VHOST_FILE: ${VHOST_FILE}
    volumes:
      - ./:/var/www
    ports:
      - 80
    restart: unless-stopped
    depends_on:
      - mktp-web-node
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOSTS}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${VIRTUAL_HOSTS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - nginx-proxy
      - mktp

  mktp-web-node:
    container_name: mktp-web-node
    command: /bin/sh ${ENTRYPOINT}
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
      - ../nginx-proxy/certs:/etc/certs
    restart: unless-stopped
    ports:
      - 60035:60035
    networks:
      - mktp

networks:
  mktp:
    external: true
  nginx-proxy:
    external: true
